### PR TITLE
Refactor testFindOvershadowedBy test case to improve readability

### PR DESCRIPTION
**Pull request by Codegass**
### Description

This pull request refactors the test case [testFindOvershadowedBy](https://github.com/apache/druid/tree/master/core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java#L126) in test class OvershadowableManagerTest. Currently, this test case combines 2 different test scenarios for the Zookeeper port initialization. The refactoring breaks this test case down into 2 separate test cases, each of which focuses on one scenario. This will help developers to  test more the potential issues in one CI\CD cycle.

<hr>

##### Motivation

The original test case use the one long arrangement to test two different cases for the findOvershadowedBy() method, by extracting the arrangement as one setup method in the class and splitting the test case to two unit test cases with specific name, the readability of the test case is improved. Also, this will help the developer to locate more issue in one CI/CD cycle.

##### Key changed/added classes in this PR
- Replace the [testFindOvershadowedBy](https://github.com/apache/druid/tree/master/core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java#L126) test case with 2 unit test, each unit test case is named based on the test target and its specific action or parameter in the testing:
  - [testFindOvershadowedByOvershadowed](https://github.com/Codegass/druid/tree/refactor-testfindovershadowedby/core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java#126)
  - [testFindOvershadowedByVisible](https://github.com/Codegass/druid/tree/refactor-testfindovershadowedby/core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java#L142)
- Extract the test arrangement section as [setupFindOvershadowedBy](https://github.com/Codegass/druid/tree/refactor-testfindovershadowedby/core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java#L1097) method.
<hr>

This PR has:
- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.

### CODE REVIEW

**Comment by Codegass** [comment]
I removed the 

```java
final List<PartitionChunk<OvershadowableInteger>> expectedOvershadowedChunks = new ArrayList<>();
```

in the arrangement, cause I didn't see the necessary of this re-claim and it will make the refactor more complicated.

Correct me if I am wrong.

**Comment by lxiao6** [comment]
The refactoring breaks this test case down into 2 separate test cases, each of which focuses on one scenario.

Need to say what are these two scenarios.

**Comment by lxiao6** [comment]
remove This will help developers to test more the potential issues in one CI\CD cycle. from the description

**Comment by lxiao6** [comment]
In the motivation: Also, this will help the developer to locate more issue in one CI/CD cycle. 

It does not have to be with CI/CD cycle. You can just say it is more explicit to debug when a test case fails.

**Comment by lxiao6** [comment]
link to [testFindOvershadowedByOvershadowed](https://github.com/Codegass/druid/tree/refactor-testfindovershadowedby/core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java#126) is not working somehow

**Comment by lxiao6** [comment]
> I removed the
> 
> ```java
> final List<PartitionChunk<OvershadowableInteger>> expectedOvershadowedChunks = new ArrayList<>();
> ```
> 
> in the arrangement, cause I didn't see the necessary of this re-claim and it will make the refactor more complicated.
> 
> Correct me if I am wrong.

I saw that expectedOvershadowedChunks is used in the oversshadowed test case. Why do you think it can be removed?

**Pull request closed without merging**
